# don't change language to python, we are building our own python venv for build
language: shell
dist: xenial
services:
  - xvfb
before_install:
  - sudo apt-get install -y wine-stable wine32 fakeroot git curl squashfs-tools sed debmake debhelper python3-all python3-setuptools
  - virtualenv -p /usr/bin/python3 build_venv
  - source build_venv/bin/activate
  - pip3 install -r requirements.txt
  - mkdir -p ./build
script:
  # Debian
  - echo $DISPLAY
  - exit 100
  #- python3 setup.py --command-packages=stdeb.command bdist_deb
  #- ls dist/*
  #- cp dist/*tar.gz build/
  # Windows
  - wget https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe
  - wine python-3.8.2-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
  - wine pip install pyinstaller
  - wine pip install -r requirements.txt
  - wine python build_win32.py build
  # GCW-Zero
  # - cd dist
  # - tar xvfz tuxemon*.tar.gz
  # cd fails
  # - cd tuxemon*
  # - sed -i 's/resolution_x.*/resolution_x = 320/g' tuxemon/tuxemon.cfg
  # - sed -i 's/resolution_y.*/resolution_y = 240/g' tuxemon/tuxemon.cfg
  # - sed -i 's/fullscreen.*/fullscreen = 1/g' tuxemon/tuxemon.cfg
  # - cp tuxemon/resources/gfx/icon_32.png tuxemon/resources/gfx/icon.png
  # - mksquashfs tuxemon ./build/tuxemon-unstable-latest.opk -all-root -noappend -no-exports -no-xattrs
deploy:
  provider: s3
  access_key_id: AKIAJCO54X2SZSP2HYCA
  secret_access_key:
    secure: IvdL4/le7EuQj7qepYWB4TcQAlkishk8k/B4Dxx2X7jmNSpFW8paoe/K+wTxNdbknikTgoUIqAbi93s8HczIlHPOdKPaCUVFr5YgaP5vRxu0AvSLMrs04ZdOpidVRSXHajGC7oCSe62TQf+lJbNJ/ZXUVjjNApPIPH46x45pZ1E3M3fwGn9bBVP7+ju8q7AZJqZIwalI24A4qk9jHUZoYUuOKToJmPAus9s4Lsp4xKAw3XTaJYdlWKZ/y5st+1+6a/8qBpBBifCYThWDIYq27BhNAK2W4Nvm8+YjYCbkYMpQxRXKZCl1YUO4RzpHcpYniNgKI0kwxWhY6lA9WeXcS98GldH5oJdaIvdorp1JQMU4pyom3FwOmwRMbIoKfKYKW7x9kjTmEzWg5pdfSEDYby1zVciEyjuVtqP1esEnhljMPlKEBjPVObfdz8mZSUcYss46k+y8Fgqfgkng0QP83YCVC8izTPJOCjfdCfn+tirbdMQbKk2MQ5eK0vFQlghgYc232LprJoPYVW6x5lNV25s9IZnppDd7zGo7DUe2ObKEZBzkmdAmM4RANnQrbzr+SEuKA9gbAUnlrpBNK+n1NkdJn7ya1JynvbyiIG5+JfY9Z4R00gHOUu+/Hy3bMg++QnGoSdipn2M9M6NBvzerpqzg754XL6q5pzNM7XmoG5c=
  bucket: tuxemon
  skip_cleanup: true
  acl: 'public_read'
  local_dir: build
  on:
    repo: Tuxemon/Tuxemon
    branch: development
